AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:
 SampleFunction1:
  Type: AWS::Serverless::Function
  Properties:
   Handler: lambda_function.lambda_handler
   Runtime: python3.7
   FunctionName: cp-search-photos
   CodeUri: ./search-photos #Directory the source file is
   Policies:
      # Give the Lambda service access to poll your DynamoDB Stream
      - AmazonLexFullAccess
 
 SampleFunction2:
  Type: AWS::Serverless::Function
  Properties:
   Handler: lambda_function.lambda_handler
   Runtime: python3.7
   FunctionName: cp-index-photos
   CodeUri: ./index-photos #Directory the source file is